##### PREFIX & KEYBINDINGS #####

# Change prefix from C-b to C-x
unbind C-b
set -g prefix C-x
bind C-x send-prefix

# Split panes (keep current path)
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
unbind '"'
unbind '%'

# New window in same path
bind c new-window -c "#{pane_current_path}"

# Reload config
bind r source-file ~/.tmux.conf \; display-message "Reloaded ~/.tmux.conf"

# Pane navigation with Alt + hjkl
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

##### COPY / PASTE SETTINGS #####

# Vi style copy mode
setw -g mode-keys vi
unbind ]
bind [ copy-mode

# Vi copy mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
bind-key -T copy-mode-vi Y send-keys -X copy-end-of-line

bind P paste-buffer

##### TERMINAL #####################################################

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

set -g mouse on
set -g status-position top
set -g status-interval 5
set -g renumber-windows on

# Keep tmux window names stable
set-window-option -g allow-rename off
set-window-option -g automatic-rename off

##### PLUGINS ######################################################

set -g @plugin "tmux-plugins/tpm"
set -g @plugin 'catppuccin/tmux#v2.3.1'
set -g @plugin "tmux-plugins/tmux-yank"

##### CATPPUCCIN ##################################################

set -g @catppuccin_flavor "mocha"

# Window styling
set -g @catppuccin_window_status_style "rounded"

# Separators
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator ""
set -g @catppuccin_window_middle_separator "│"

# Status bar
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator ""

# Status bar
set -g status-left ""
set -g @catppuccin_status_modules_right "host date_time"
set -g @catppuccin_window_text "#{window_name}"
set -g @catppuccin_window_current_text "#{window_name}"
set -g status-right "#{E:@catppuccin_status_session} #{E:@catppuccin_status_host} #{E:@catppuccin_status_date_time}"
##### TPM — KEEP LAST ###############################################

# Initialize TPM (keep at bottom)
run "~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux"
# source-file "~/.config/tmux/plugins/tmux-themepack/powerline/default/gray.tmuxtheme"
run '~/.tmux/plugins/tpm/tpm'
