##### KEYBINDS / BEHAVIOR #####

# Change prefix from C-b to C-x
unbind C-b
set -g prefix C-x
bind C-x send-prefix

# Split panes
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"
unbind '"'
unbind '%'

# New window in same path
bind c new-window -c "#{pane_current_path}"

# Reload config
bind r source-file ~/.tmux.conf \; display-message "Reloaded ~/.tmux.conf"
##### COPY / PASTE SETTINGS #####

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-dir '~/.tmux/resurrect'
setw -g mode-keys vi
unbind ]
bind P paste-buffer
bind [ copy-mode


# Vi copy mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
bind-key -T copy-mode-vi Y send-keys -X copy-end-of-li

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Disable automatic renaming of windows
set-option -g allow-rename off
set-option -g automatic-rename off

# Terminal settings
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

set -g @plugin 'fabioluciano/tmux-powerkit'

# Basic configuration
set -g @powerkit_plugins "datetime,hostname"
# Choose your separator styl# Tokyo Night - Night variant
set -g @powerkit_theme "tokyo-night"
set -g @powerkit_theme_variant "night"

set -g @powerkit_separator_style "normal"  # or normal, flame, pixel, honeycomb, rounded, slant, slantup

# Enable spacing beteen elements
set -g @powerkit_elements_spacing "both"

# Customize update interval
set -g @powerkit_status_interval "5"

# Make it transparent
set -g @powerkit_transparent "true"

set -g @powerkit_plugin_git_icon ""
set -g @powerkit_plugin_git_show_branch "true"
set -g @powerkit_plugin_git_show_files "true"
set -g @powerkit_plugin_git_max_length "30"
set -g @powerkit_plugin_datetime_format "%Y-%m-%d %H:%M:%S"  # %Y-%m-%d %H:%M:%S

set -g status-position top
set -g renumber-windows on

# Initialize TPM (keep at bottom)
run -b '~/.tmux/plugins/tpm/tpm'
run ~/.tmux/plugins/tmux-powerkit/tmux-powerkit.tmux
bind-key C-s run-shell ~/.tmux/plugins/tmux-resurrect/scripts/save.sh
bind-key C-r run-shell ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh
