[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark_hard.toml"
    # "~/.config/alacritty/themes/themes/everforest_medium.toml"
    # "~/.config/alacritty/themes/themes/everforest_dark_soft.toml"
]
[font]
size = 16.0
